### ISSUE TITLE
navbar-toggler-icon does not follow the color scheme

### ISSUE THREAD

**Issue by zessx** [zessx/twbscolor#2]
`.navbar-toggler-icon` use a SVG as a background image.

It needs to be update with the front color:
```css
.navbar .navbar-toggler .navbar-toggler-icon {
    background-image: url("data:image/svg+xml,%3csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3e%3cpath stroke='rgba(255, 255, 255)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e");
}
```
